# Generated by Django 4.0.5 on 2022-06-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=50)),
                ('brand', models.CharField(default='brand not found', max_length=20)),
                ('description', models.TextField()),
                ('price', models.IntegerField(max_length=6)),
                ('on_sale', models.BooleanField(default=False)),
            ],
        ),
    ]
