# Generated by Django 4.0.5 on 2022-07-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_excess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemreview',
            old_name='monitor',
            new_name='item',
        ),
    ]
