# Generated by Django 4.0.5 on 2022-06-30 01:55

from django.db import migrations

def seed(apps, schema_editor):
    Monitors = apps.get_model('tech_excess', 'Monitors')


    Monitors(title = 'LG 34WN750-B Monitor 34"', brand='LG', description='no description yet', price = 496, on_sale = False, featured_image_url = 'https://i.imgur.com/rudh6sm.jpg', image_urls=['https://i.imgur.com/zOskYQF.jpeg', 'https://i.imgur.com/c6GqBiS.jpg']).save() 
    Monitors(title = 'Alienware 240Hz Gaming Monitor 24.5"', brand='Alienware', description='no description yet', price = 266, on_sale = True, featured_image_url = 'blob:https://imgur.com/a2e2d422-fcbd-4ac8-895d-5dd939611003', image_urls=['https://i.imgur.com/IvIMQBY.jpg']).save() 
    Monitors(title = 'ASUS ROG Strix 34"', brand='ASUS', description='no description yet', price = 799, on_sale = False, featured_image_url = 'https://i.imgur.com/D36qxYq.jpg', image_urls=['https://i.imgur.com/D36qxYq.jpg']).save() 

def fallow(apps, schema_editor):
    Monitors = apps.get_model('tech_excess', 'Monitors')
    Monitors.objects.all().delete()

    

class Migration(migrations.Migration):

    dependencies = [
        ('tech_excess', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
