# Generated by Django 4.0.5 on 2022-06-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_excess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitors',
            name='image_url',
            field=models.CharField(default='No image', max_length=500),
        ),
        migrations.AlterField(
            model_name='monitors',
            name='price',
            field=models.IntegerField(),
        ),
    ]
