# Generated by Django 4.0.5 on 2022-07-07 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tech_excess', '0002_rename_monitor_itemreview_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreview',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
