# Generated by Django 4.0.5 on 2022-06-28 02:28

from django.db import migrations


def seed(apps, schema_editor):
    Monitors = apps.get_model('tech_excess', 'Monitors')


    Monitors(title = 'LG 34WN750-B Monitor 34"', brand='LG', description='no description yet', price = 496, on_sale = False, image_url='https://i.imgur.com/zOskYQF.jpeg').save() 
    Monitors(title = 'Alienware 240Hz Gaming Monitor 24.5"', brand='Alienware', description='no description yet', price = 266, on_sale = True, image_url='https://i.imgur.com/IvIMQBY.jpg').save() 
    Monitors(title = 'ASUS ROG Strix 34"', brand='ASUS', description='no description yet', price = 799, on_sale = False, image_url='https://i.imgur.com/D36qxYq.jpg').save() 

def fallow(apps, schema_editor):
    Monitors = apps.get_model('tech_excess', 'Monitors')
    Monitors.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('tech_excess', '0002_monitors_image_url_alter_monitors_price'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
