# Generated by Django 4.0.6 on 2022-07-11 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tech_excess', '0003_itemreview_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemreview',
            name='owner',
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
