# Generated by Django 4.0.5 on 2022-07-04 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_excess', '0005_headphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='unknown', max_length=50)),
                ('body', models.TextField()),
                ('rating', models.IntegerField()),
                ('headphone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headphone', to='tech_excess.headphone')),
                ('keyboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyboard', to='tech_excess.keyboard')),
                ('monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor', to='tech_excess.monitors')),
                ('mouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouse', to='tech_excess.mouse')),
            ],
        ),
    ]
