# Generated by Django 4.0.5 on 2022-07-04 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_excess', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='headphone',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headphone', to='tech_excess.headphone'),
        ),
        migrations.AlterField(
            model_name='review',
            name='keyboard',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyboard', to='tech_excess.keyboard'),
        ),
        migrations.AlterField(
            model_name='review',
            name='monitor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor', to='tech_excess.monitors'),
        ),
        migrations.AlterField(
            model_name='review',
            name='mouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouse', to='tech_excess.mouse'),
        ),
    ]
