# Generated by Django 4.0.6 on 2022-07-14 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_excess', '0007_alter_wishlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='wishlists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='tech_excess.wishlist'),
        ),
    ]
