# Generated by Django 4.0.5 on 2022-07-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_excess', '0008_alter_review_headphone_alter_review_keyboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='headphone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tech_excess.headphone'),
        ),
        migrations.AlterField(
            model_name='review',
            name='keyboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tech_excess.keyboard'),
        ),
        migrations.AlterField(
            model_name='review',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tech_excess.monitors'),
        ),
        migrations.AlterField(
            model_name='review',
            name='mouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tech_excess.mouse'),
        ),
    ]
