# Generated by Django 4.0.5 on 2022-07-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_excess', '0009_alter_review_headphone_alter_review_keyboard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='unknown', max_length=50)),
                ('body', models.TextField()),
                ('rating', models.IntegerField()),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tech_excess.monitors')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
