# Generated by Django 4.0.6 on 2022-07-16 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_excess', '0010_cart_item_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='owner',
        ),
    ]
