# Generated by Django 4.0.5 on 2022-07-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_excess', '0010_monitorreview_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorreview',
            name='monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_reviews', to='tech_excess.monitors'),
        ),
    ]
