# Generated by Django 4.0.5 on 2022-07-04 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_excess', '0011_alter_monitorreview_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorreview',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tech_excess.monitors'),
        ),
    ]
